
- name: Restart clamav services
  service:
    name: '{{ service }}'
    state: restarted
    enabled: yes
  with_items:
    - clamsmtp
    - clamav-daemon
  loop_control:
    loop_var: service

- name: Restart AppArmor service
  service:
    name: apparmor
    state: reloaded
