---

sieve:
  global_scripts:
    - duplicate-checks.sieve
    - sent-checks.sieve
    - before-global.sieve
    - report-spam.sieve
    - report-ham.sieve
    - tags-important.sieve

# Default dovecot packages to install
dovecot:
  packages:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-pop3d
    - dovecot-managesieved
    - dovecot-sieve
    - dovecot-ldap
  settings:
    mail_max_userip_connections: 64
    lda_mailbox_autocreate: no
    lda_mailbox_autosubscribe: no
