---

# Remove packages that are not needed for a live system:
# bash-completion:
# See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825153
# this seems to remove most errors like :
# <passwd="*"> request denied by validnames option.

- name: Remove useless packages
  tags: apt
  apt:
    name: '{{ pkg }}'
    state: absent
  with_items:
    - bash-completion
  loop_control:
    loop_var: pkg


# At this point, it might be necessary to reboot
# To reload all bash instances
