# Host files for the homebox project
# Choose the box that will host the system
# It might be a virtual machine host or even your local machine.

all:
  hosts:
    homebox:
      ansible_host: box.zvea.co
      ansible_user: root
      ansible_port: 22
