# HomeBox configuration example.
# Copy this file into config.yml, and edit it with the values that suits you
# For a more comprehensive list of settings, you can see the default file in
#

###############################################################################
# Domain and hostname information
network:
  domain: zvea.co
  hostname: box.zvea.co


# LDAP configuration
# ldap:
#   hostname: 'ldap.{{ network.domain }}'
#   organization:
#     domain: '{{ network.domain }}'
#     base: 'dc={{ network.domain | regex_replace("\.", ",dc=") }}'
#   users:
#     dn: 'ou=users,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
#   groups:
#     dn: 'ou=groups,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
#   manager:
#     uid: manager
#     dn: 'cn=manager account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
#   readonly:
#     uid: readonly
#     dn: 'cn=readonly account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
#   admin:
#     dn: 'cn=admin,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
#     desc: administrator account
#   postmaster:
#     uid: postmaster
#     dn: 'cn=postmaster account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
#     # See https://www.ietf.org/rfc/rfc2142.txt
#     mailAliases:
#       - 'abuse@{{ network.domain }}'
#       - 'noc@{{ network.domain }}'
#       - 'security@{{ network.domain }}'
#       - 'mailer-daemon@{{ network.domain }}'
#       - 'webmaster@{{ network.domain }}'
#       - 'hostmaster@{{ network.domain }}'
#       - 'admin@{{ network.domain }}'
#       - 'root@{{ network.domain }}'

#   # password params
#   roPasswdParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/ldap/readonly.pwd {{ policies.system.password }}"
#   managerPasswdParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/ldap/manager.pwd {{ policies.system.password }}"
#   adminPasswdParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/ldap/admin.pwd {{ policies.system.password }}"
#   postmasterPasswdParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/ldap/postmaster.pwd {{ policies.system.password }}"

###############################################################################
# Users
# List of users to create in the system
users:
- uid: john
  cn: John Doe
  first_name: John
  last_name: Doe
  mail: mattias@zvea.co
  password: testtest

###############################################################################
# Email related default options
mail:
  max_attachment_size: 25   # In megabytes
  autoconfig: true          # Support Thunderbird automatic configuration
  autodiscover: false       # Support MS Outlook automatic configuration (uses https)
  quota:
    default: 1G             # Maximum allowed mailbox size for your users.
                            # The safe maximum value will be automatically computed in a next version.
  discard_duplicates: true  # Discard duplicates messages. It is safe, but you can disable if you are worried
#                             # The default timerange is 1h
#   #############################################################################
  antivirus:                # Check inbound and outbound emails for viruses
    active: true            # or false
    action: drop            # Action to do when a virus is found in an email: bounce or drop
                             # be careful, bouncing external emails is a way to expose clamav usage
    send_warnings: false    # Send a warning email to - internal - users who are sending viruses
    quarantine: yes         # Place emails with a virus in quarantine, for further analysis
#   #############################################################################
  impersonate:              # Activate dovecot "master" user feature, ideal for families and communities
    active: true           # https://wiki2.dovecot.org/Authentication/MasterUsers
    master: master          # master user name
    separator: '*'          # Separation char between master user / real user name.
#   #############################################################################
  import:                   # If you have users with "import" email active scripts, set this flag to true
    username: import        # The name of the user that import emails
    active: false           # A master user, with reduced rights will be created, to append miported emails
#                             # in user's mailboxes.
#   #############################################################################
#   # Dovecot / solr FTS (Full Text search)
  fts:
    active: true
    langs:
      - id: sv
        name: Swedish
      - id: en
        name: English
#   #############################################################################
#   advanced_features: false  # Use some advanced features that will need the latest version of dovecot
#                             # from stretch-backports, like those below.
#                             # like sending emails to an international addresses (e.g. andré@homebox.space)
#   recipient_delimiter: '+'  # The characters you want to use to split email address from mailbox, i.e.:
#                             # when receiving a message to john+lists@example.com, it should go directly to
#                             # the 'lists' folder...
#############################################################################
# Allows you to configure postfix completely
#   postfix_add: |
#     # Send emails to another domain
#     recipient_bcc_maps = regexp:/etc/postfix/recipient_bcc

###############################################################################
# System related

system:
  release: stretch
  login: true
  ssl: letsencrypt
  devel: true
  debug: true


###############################################################################
# Gandi automatic DNS update
# Your Gandi Key should be 24 characters long, e.g. zaNGbUVIvi1KbYb6PPMdiQLh
# dns:
#   update: false         # Automatic update of your DNS server
#   test: true            # test mode: does not activate the DNS zone straight
#   add_wildcard: false   # Create a wildcard entry to redirect all traffic to your box
#   gandi:
#     handle: JD123-GANDI
#     key: zaNGbUVIvi1KbYb6PPMdiQLh

###############################################################################
# Once the system is in place, it is possible to use 'limit' for the rule, instead of any.
# It is also possible to use fail2ban, which is installed anyway
# firewall:
#   ssh:
#     from: any
#     rule: allow

###############################################################################
# Install a webmail, or not...
webmail:
  install: true
  type: roundcube

###############################################################################
# Extra security values
security:
   auto_update: true
   app_armor: false

###############################################################################
# Backup configuration
# You can have multiple backup configuration:
# remote (ssh or samba) and local directory
# All backups will be encrypted
# Compression: See borg documentation

backup:
  install: false
  type: borgbackup
#   locations:

# Exemple 1: backup on the local disk. Useful for small backup only
#   - name: local
#     url: dir://var/backups/homebox
#     active: yes                      # The backup is currently active
#     frequency: daily                 # Run the backup every day
#     keep_daily: 3                    # Keep the last three days locally
#     compression: lz4                 # Compression scheme to use (lz4 by default)

# Example 2: Backup on a remote location, over SSH
#   - name: router
#     url: ssh://fw.office.pm:/home/backup/homebox
#     active: yes                      # The backup is currently active
#     frequency: daily                 # Run the backup every day
#     keep_daily: 7                    # Keep the last seven days (default value)
#     keep_weekly: 4                   # Keep the last four weeks (default value)
#     keep_monthly: 6                  # Keep the last six months (12 by default)
#     compression: lz4                 # Compression scheme to use (lz4 by default)

# Example 3: Backup on a network NAS mounted via Samba / CIFS
#   - name: nas
#     url: smb://backup:giuwh97kwerr@ftp.office.pm:/home/backup/homebox
#     active: yes                      # The backup is currently active
#     frequency: weekly                # Run the backup every week
#     keep_weekly: 4                   # Keep the last four weeks (default value)
#     keep_monthly: 6                  # Keep the last six months (12 by default)
#     compression: zlib,6              # Compression scheme to use (lz4 by default)

# Exemple 4: Backup on a USB stick labelled as "backup", when inserted or periodically
#   - name: usb-backup
#     url: usb://media/backup/
#     active: yes                      # The backup is currently active
#     frequency: weekly                # Run the backup every week
#     keep_weekly: 4                   # Keep the last four weeks (default value)
#     keep_monthly: 6                  # Keep the last six months (12 by default)
#     compression: zlib,6              # Compression scheme to use (lz4 by default)


###############################################################################
# Dictionaries to install in the system, will be displayed in roundcube for now.
dictionaries:
  - name: English
    id: en
  - name: Swedish
    id: sv