---
# Cleanup the system, make it ready for production, remove development packages

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  roles:
    - dev-cleanup
