---
# Prepare the remote system for development

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/defaults.yml'
    - '{{ playbook_dir }}/../../config/system.yml'
  roles:
    - dev-support
