---

# Generate the records on the DNS server
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  vars:
    verbose: True
  roles:
    - load-defaults
