---

# Install bind9 DNS server
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/defaults.yml'
    - '{{ playbook_dir }}/../../config/system.yml'
  roles:
    - dns-server-bind-refresh
