---

# Read or detect the external IP address
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
    - '{{ playbook_dir }}/roles/ldap/variables/main.yml'
  roles:
    - external-ip
