---

# Install a minimal SSH server to remotely unlock the system, via SSH
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  roles:
    - luks-remote
