---
## Main installation playbook

# Load default settings once, this is needed to defined
# some conditional flags used below
- import_playbook: load-defaults.yml

# Complete list of playbooks to run, in this order
- import_playbook: external-ip.yml
- import_playbook: system-prepare.yml
- import_playbook: remote-access.yml

# Install fwknop (Single Packet Authorization)
- import_playbook: fwknop-client.yml
  when: firewall.fwknop.install
- import_playbook: fwknop-server.yml
  when: firewall.fwknop.install

# Install dropbear to remotely unlock the system.
# Will not do anything if the drive is not encrypted
- import_playbook: luks-remote.yml

# Install nginx as the default web server,
# it is needed to obtain certificates with certbot.
- import_playbook: nginx.yml

# Install the DNS server first if requested
#- import_playbook: dns-server-bind.yml
#  when: bind.install

## Check if the DNS entries are now propagated on internet
#- import_playbook: dns-server-check-propagation.yml
#  when: bind.install

# At this point, if you have installed bind,
# perhaps you should wait a few hours until
# the DNS propagation is complete.

# Start to create users and home directories
#- import_playbook: ldap.yml
- import_playbook: homes.yml

# Configure SSH for remote access using borgbackup,
# But only for users with an ssh key provided.
# See system-example.yml configuration file
#- import_playbook: backup-server.yml

# System protection: antispam
- import_playbook: rspamd.yml
  when: mail.antispam.active
- import_playbook: rspamd-web.yml
  when: mail.antispam.webui.active
- import_playbook: clamav.yml
  when: mail.antivirus.active

# Email server: MTA
- import_playbook: opendkim.yml
- import_playbook: opendmarc.yml
- import_playbook: cert-smtp.yml
- import_playbook: postfix.yml

# Create DNS entries (Only Gandi for now)
# - import_playbook: dns-update.yml
#   when: not bind.install

# Mail delivery agent (dovecot)
- import_playbook: cert-pop3.yml
- import_playbook: cert-imap.yml
- import_playbook: dovecot.yml

# Install the selected webmail
- import_playbook: roundcube.yml
  when: webmail.install and webmail.type == 'roundcube'


# Install a simple but secure (https) web site skeleton
- import_playbook: website-simple.yml
  when: website.install

# Automatic configuration for email clients.
- import_playbook: autodiscover.yml
  when: mail.autodiscover
- import_playbook: autoconfig.yml
  when: mail.autoconfig


# Build the complete DNS server zones file
#- import_playbook: dns-server-bind-refresh.yml
#  when: bind.install

# Clean up the system before going live
- import_playbook: system-cleanup.yml
