---

################################################################################
# Get the external IP address, from configuration file,
# or automatically through a script

- name: Copy the configuration file
  when: network.external_ip == "auto"
  tags: scripts
  copy:
    src: external-ip.conf
    dest: /etc/external-ip.conf

- name: Copy the external IP address detection script
  when: network.external_ip == "auto"
  tags: scripts
  copy:
    src: external-ip
    dest: /usr/local/bin/external-ip
    mode: 0755

- name: Run the script to get the external IP address automatically
  tags: facts
  when: network.external_ip == "auto"
  register: external_ip_facts
  shell: /usr/local/bin/external-ip -u /etc/external-ip.conf

- name: Get the external IP address automatically
  tags: facts
  when: network.external_ip == "auto"
  set_fact:
    external_ip: '{{ external_ip_facts.stdout }}'

- name: Get the external IP address automatically
  tags: facts
  when: network.external_ip != "auto"
  set_fact:
    external_ip: '{{ network.external_ip }}'

- name: Set external IP address type (A or AAAA)
  tags: facts
  register: main_ip_type
  shell:
    echo {{ external_ip }}
    | grep -E '^[0-9\.]+$' 2>&1 >/dev/null
    && echo A || echo AAAA

- name: Set external IP address type (A or AAAA)
  tags: facts
  set_fact:
    external_ip_type: '{{ (main_ip_type.stdout) }}'

- name: Get the backup IP address
  when: network.backup_ip != None
  tags: facts
  set_fact:
    backup_ip: '{{ network.backup_ip }}'

- name: Set external IP address type (A or AAAA)
  when: network.backup_ip != None
  tags: facts
  register: backup_ip_type
  shell:
    echo {{ backup_ip }}
    | grep -E '^[0-9\.]+$' 2>&1 >/dev/null
    && echo A || echo AAAA

- name: Set external IP address type (A or AAAA)
  tags: facts
  when: network.backup_ip != None
  set_fact:
    backup_ip_type: '{{ (backup_ip_type.stdout) }}'
