---

- name: Install opendmarc related packages
  tags: opendmarc
  apt:
    name: '{{ pkg }}'
    state: latest
  loop:
    - opendmarc

- name: Comment all active socket for DMARC
  tags: opendmarc
  notify: Restart OpenDMARC service
  replace:
    path: /etc/default/opendmarc
    regexp: '^SOCKET=(.*)'
    replace: '#SOCKET=\1'

- name: Comment all active socket for DMARC
  tags: opendmarc
  notify: Restart OpenDMARC service
  replace:
    path: /etc/opendmarc.conf
    regexp: '^Socket(.*)'
    replace: '# Socket=\1'

- name: Add tcp interface on localhost
  notify: Restart OpenDMARC service
  tags: opendmarc
  lineinfile:
    path: /etc/opendmarc.conf
    line: '{{ line }}'
  with_items:
    - 'Socket inet:{{ dmarc.milter.port }}@localhost'
    - 'AutoRestart 1'
  loop_control:
    loop_var: line

- name: Generate DMARC record from settings
  tags: bind
  when: bind.install
  template:
    src: 20-dmarc.bind
    dest: /etc/homebox/dns-entries.d/20-dmarc.bind
