---

roundcube:
  url: 'webmail.{{ network.domain }}'
  title: 'Roundcube Webmail ({{ ldap.organization.domain }})'
  enigma: no
  max_attachment_size: 25   # In megabytes
  plugins: '{{ roundcube_plugins }}'
